openapi: 3.0.1
info:
  title: API de Categorias
  description: Uma Api do Json-server para fins didáticos
  version: 0.0.1
  termsOfService: https://siteparaservicos.com
  contact:
    name: Suporte a Devs
    email: contato@example.com
    url: https://siteparaservicos.com
  license:
    name: "Licença para rodar Api"
    url: https://siteparalicencas.com
externalDocs:
  description: Documentação burocrática
  url: https://siteparadocumentaçãextra.com
servers:
- url: http://localhost:3000
  description: API de Teste
- url: http://localhost:3001
  description: API de producao
paths:
  /categories:
    get:
      summary: Recupera todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string
  /admin/categories:
    post:
      summary: Cria uma nova categorias
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string
  /categories/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    get:
      summary: Recupera uma categoria pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not Found"
  /admin/categories/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    put:
        summary: Altera dados de uma categoria pelo ID
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  status:
                    type: string
        responses:
          200:
            description: Sucesso
            content:
              application/json:
                schema:
                    type: object
                    properties:
                      id:
                        type: integer
                      nome:
                        type: string
                      status:
                        type: string
          404:
            description: Categoria não encontrada
            content:
              application/sjon:
                example: "Not Found"
    patch:
        summary: Ativa  uma categoria pelo ID
        responses:
          200:
            description: Sucesso
            content:
              application/json:
                schema:
                    type: object
                    properties:
                      id:
                        type: integer
                      nome:
                        type: string
                      status:
                        type: string
                        
          404:
            description: Categoria não encontrada
            content:
              application/sjon:
                example: "Not Found"
    delete:
        summary: Remove uma categoria pelo ID
        responses:
          204:
            description: Sucesso
          404:
            description: Categoria não encontrada
            content:
              application/sjon:
                example: "Not Found"