openapi: 3.0.1
info:
  title: API Json-server 
  description: Uma Api do Json-server para fins didáticos
  version: 0.0.1
  termsOfService: https://siteparaservicos.com
  contact:
    name: Suporte a Devs
    email: contato@example.com
    url: https://siteparaservicos.com
  license:
    name: "Licença para rodar Api"
    url: https://siteparalicencas.com
externalDocs:
  description: Documentação burocrática
  url: https://siteparadocumentaçãextra.com
servers:
- url: http://localhost:3000
  description: API de Teste
- url: http://localhost:3001
  description: API de producao
paths:
  /categories:
    get:
      summary: Recupera todas as categorias
      tags: 
        - Category
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string
  /admin/categories:
    post:
      summary: Cria uma nova categorias
      tags: 
        - Category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string
  /categories/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    get:
      summary: Recupera uma categoria pelo ID
      tags: 
        - Category
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    status:
                      type: string
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not Found"
  /admin/categories/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    put:
        summary: Altera dados de uma categoria pelo ID
        tags: 
        - Category
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  status:
                    type: string
        responses:
          200:
            description: Sucesso
            content:
              application/json:
                schema:
                    type: object
                    properties:
                      id:
                        type: integer
                      nome:
                        type: string
                      status:
                        type: string
          404:
            description: Categoria não encontrada
            content:
              application/sjon:
                example: "Not Found"
    patch:
        summary: Ativa  uma categoria pelo ID
        tags: 
        - Category
        responses:
          200:
            description: Sucesso
            content:
              application/json:
                schema:
                    type: object
                    properties:
                      id:
                        type: integer
                      nome:
                        type: string
                      status:
                        type: string
                        
          404:
            description: Categoria não encontrada
            content:
              application/sjon:
                example: "Not Found"
    delete:
        summary: Remove uma categoria pelo ID
        tags: 
        - Category
        responses:
          204:
            description: Sucesso
          404:
            description: Categoria não encontrada
            content:
              application/sjon:
                example: "Not Found"
  /product:
    get:
      summary: Recupera todos os produtos
      tags: 
        - Product
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    descricao:
                      type: string
                    slug:
                      type: string
                    preco_unitario:
                      type: string
                    estoque:
                      type: string
                    _idCategoria:
                      type: string
  /admin/product:
    post:
      summary: Cria um novo produto
      tags: 
        - Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
                slug:
                  type: string
                preco_unitario:
                  type: string
                estoque:
                  type: string
                _idCategoria:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    descricao:
                      type: string
                    slug:
                      type: string
                    preco_unitario:
                      type: string
                    estoque:
                      type: string
                    _idCategoria:
                      type: string
  /product/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    get:
      summary: Recupera um produto pelo ID
      tags: 
        - Product
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    descricao:
                      type: string
                    slug:
                      type: string
                    preco_unitario:
                      type: string
                    estoque:
                      type: string
                    _idCategoria:
                      type: string
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not Found"
  /admin/product/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    put:
        summary: Altera dados de um produto pelo ID
        tags: 
        - Product
        requestBody:
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    nome:
                      type: string
                    descricao:
                      type: string
                    slug:
                      type: string
                    preco_unitario:
                      type: string
                    estoque:
                      type: string
                    _idCategoria:
                      type: string
        responses:
          200:
            description: Sucesso
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    descricao:
                      type: string
                    slug:
                      type: string
                    preco_unitario:
                      type: string
                    estoque:
                      type: string
                    _idCategoria:
                      type: string
          404:
            description: Categoria não encontrada
            content:
              application/sjon:
                example: "Not Found"
   
    delete:
        summary: Remove um produto pelo ID
        tags: 
        - Product
        responses:
          204:
            description: Sucesso
          404:
            description: Categoria não encontrada
            content:
              application/sjon:
                example: "Not Found"
  /user:
    get:
      summary: Recupera todos os usuarios
      tags: 
        - User
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    email:
                      type: string
                    senha:
                      type: string
                    cpf:
                      type: string
                    telefone:
                      type: string
                    rua:
                      type: string
                    numero:
                      type: string
                    cep:
                      type: string
                    cidade:
                      type: string
                    estado:
                      type: string
  /admin/user:
    post:
      summary: Cria um novo usuario
      tags: 
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                senha:
                  type: string
                cpf:
                  type: string
                telefone:
                  type: string
                rua:
                  type: string
                numero:
                  type: string
                cep:
                  type: string
                cidade:
                  type: string
                estado:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    email:
                      type: string
                    senha:
                      type: string
                    cpf:
                      type: string
                    telefone:
                      type: string
                    rua:
                      type: string
                    numero:
                      type: string
                    cep:
                      type: string
                    cidade:
                      type: string
                    estado:
                      type: string
  /user/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    get:
      summary: Recupera um usuario pelo ID
      tags: 
        - User
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    email:
                      type: string
                    senha:
                      type: string
                    cpf:
                      type: string
                    telefone:
                      type: string
                    rua:
                      type: string
                    numero:
                      type: string
                    cep:
                      type: string
                    cidade:
                      type: string
                    estado:
                      type: string
        404:
          description: Usuario não encontrado
          content:
            application/json:
              example: "Not Found"
  /admin/user/{id}:
    parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
    put:
        summary: Altera dados de um usuario pelo ID
        tags: 
        - User
        requestBody:
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    nome:
                      type: string
                    email:
                      type: string
                    senha:
                      type: string
                    cpf:
                      type: string
                    telefone:
                      type: string
                    rua:
                      type: string
                    numero:
                      type: string
                    cep:
                      type: string
                    cidade:
                      type: string
                    estado:
                      type: string
        responses:
          200:
            description: Sucesso
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    email:
                      type: string
                    senha:
                      type: string
                    cpf:
                      type: string
                    telefone:
                      type: string
                    rua:
                      type: string
                    numero:
                      type: string
                    cep:
                      type: string
                    cidade:
                      type: string
                    estado:
                      type: string
          404:
            description: Usuario não encontrado
            content:
              application/sjon:
                example: "Not Found"
   
    delete:
        summary: Remove um usuario pelo ID
        tags: 
        - User
        responses:
          204:
            description: Sucesso
          404:
            description: Usuario não encontrado
            content:
              application/sjon:
                example: "Not Found"